version: '3.9'

services:
  postgres:
    container_name: postgresDB
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  app:
    build: ./
    container_name: backend
    links:
      - postgres
    ports:
      - "8080:8080"
